---
title: "Exploratory functions"
output: html_notebook
---

This notebook defines some functions that are used to explore references.
It is generally not meant to be run standalone.


Function to run `SingleR` across a few references:

```{r}
# Function to run SingleR for a given SCE for each type of reference we are evaluating here
run_singler <- function(
    sce, 
    ref_main,
    ref_title,
    ref_harmonized = harmonized_aggr,
    ref_concatenated = concatenated_aggr
  ) {
    
  # Reference that matches this sample
  res_main <- SingleR::SingleR(
    sce,
    ref_main,
    labels = ref_main$label,
    restrict = intersect(rownames(ref_main), rownames(sce)),
    BPPARAM = bp_param
  )
  
  shared_genes <- intersect(rownames(ref_harmonized), rownames(sce))

  # Harmonized reference
  res_harmonized <- SingleR::SingleR(
    sce,
    ref_harmonized,
    labels = ref_harmonized$label,
    restrict = shared_genes,
    BPPARAM = bp_param
  )
  
  # Concatenated reference
  res_concatenated <- SingleR::SingleR(
    sce,
    ref_concatenated,
    labels = ref_concatenated$label,
    restrict = shared_genes,
    BPPARAM = bp_param
  )

  # return list of results
  # this syntax allows the string that main_title hold to be used as the name
  results <- setNames(
    list(res_main, res_harmonized, res_concatenated),
    c(ref_title, "Harmonized reference", "Concatenated reference")
  )
  return(results)
}
```


Functions to plot and wrangle the output from `SingleR`:

```{r}
# Convert the DataFrame to a data.frame with only the top_n pruned.labels
get_top_n <- function(res_dataframe, top_n = 10) {
  df <- res_dataframe |> 
    as.data.frame() 
  
  # subset to top_n most frequent labels
  top_labels <- df |> 
    dplyr::count(pruned.labels, sort = TRUE) |> 
    dplyr::slice_head(n = top_n) |> 
    dplyr::pull(pruned.labels)
  
  # return
  df |> 
    dplyr::filter(pruned.labels %in% top_labels)
  
}


# Function to get and plot the label corresponding to the next highest score, for each pruned label, considering only the top_n pruned labels
plot_next_best <- function(res_dataframe, plot_title, top_n = 5) {
  next_best_df <- res_dataframe |>
    get_top_n(top_n) |>
    tibble::rownames_to_column("cell") |>
    dplyr::select(cell, pruned.labels, starts_with("scores")) |>
    tidyr::pivot_longer(
      -c(cell, pruned.labels),
      names_to = "label", 
      values_to = "score"
    ) |>
    dplyr::mutate(label = stringr::str_remove(label, "^scores\\.")) |>
    dplyr::group_by(cell) |>
    dplyr::slice_max(score, n = 2, with_ties = FALSE) |>
    dplyr::mutate(rank = c("best", "next_best")) |>
    dplyr::ungroup() |>
    tidyr::pivot_wider(names_from = rank, values_from = c(label, score)) |>
    # this is a bit of a hack because this analysis is confounded  -  the actual second best
    # score may not be the same as the second best label because of fine-tuning that isn't 
    # reflected in these scores
    dplyr::filter(label != pruned.labels)

  # update it for plot ordering
  next_best_counts <- next_best_df |>
    dplyr::count(pruned.labels, label_next_best) |>
    dplyr::mutate(
      label_next_best = tidytext::reorder_within(label_next_best, -n, pruned.labels), 
    )
  
  ggplot(next_best_counts) + 
    aes(y = label_next_best, x = n) +    
    geom_col(fill = "palevioletred4", color = "grey20", linewidth = 0.25) +
    facet_wrap(vars(pruned.labels), scales = "free") +
    labs(x = "number of cells", y = "next best label", title = plot_title) +
    tidytext::scale_y_reordered() +
    theme_bw(base_size = 8)
}

# function to plot annotation counts and delta next scores for top n recovered cell types
plot_results <- function(res_dataframe, plot_title, top_n = 10) {
  df <- get_top_n(res_dataframe)
  
  barplot <- ggplot(df) + 
    aes(y = forcats::fct_infreq(pruned.labels)) + 
    geom_bar(fill = "cornflowerblue", color = "grey20", linewidth = 0.25) +
    # put the title here instead of shared via patchwork since apparently that
    # gets overridden when I call plot_annotation() again to wrap all of these
    labs(x = "number of cells", y = "pruned label", title = plot_title) +
    theme_bw(base_size = 8) + 
    theme(plot.title = element_text(size = 8))
  

  deltanext_plot <- ggplot(df) + 
    aes(x = delta.next, y = forcats::fct_infreq(pruned.labels)) + 
    ggridges::geom_density_ridges(
      fill = "darkslategray", 
      alpha = 0.5, 
      linewidth = 0.25,
      scale = 0.95,
      # show median line
      quantile_lines = TRUE, 
      quantiles = 2, 
      # add rug
      jittered_points = TRUE,
      position = ggridges::position_points_jitter(width = 0, height = 0), # Removes vertical jitter if for a true rug
      point_shape = "|", 
      point_size = 0.2, 
      point_colour = "firebrick"
    ) +
    labs(x = "delta next", y = "pruned label") +
    theme_bw(base_size = 8)
  
  patchwork::wrap_plots(barplot, deltanext_plot)
}
```

Functions to create Jaccard similarity heatmaps:

```{r}
jaccard <- function(a, b) {
  length(intersect(a, b)) / length(union(a, b))
}


# Make a data frame of jaccard indices that we can use for a ggplot heatmap
make_jaccard_df <- function(labels1, labels2) {
  stopifnot(length(labels1) == length(labels2))
  
  ids <- seq_along(labels1)
  
  labels1 <- ifelse(is.na(labels1), "Unknown", labels1)
  labels2 <- ifelse(is.na(labels2), "Unknown", labels2)
  
  id1_list <- split(ids, labels1)
  id2_list <- split(ids, labels2)
  
  sizes1 <- lengths(id1_list)
  sizes2 <- lengths(id2_list)
  
  cross_df <- tidyr::expand_grid(id1 = names(id1_list), id2 = names(id2_list))
  
  cross_df |>
    dplyr::mutate(
      jaccard = purrr::pmap_dbl(
        cross_df,
        \(id1, id2) jaccard(id1_list[[id1]], id2_list[[id2]])
      ),
      id1_label = glue::glue("{id1} (n={sizes1[id1]})"),
      id2_label = glue::glue("{id2} (n={sizes2[id2]})")
    )
}

plot_jaccard_heatmap <- function(labels1, labels2, labels1_lab, labels2_lab) {
  
  jaccard_df <- make_jaccard_df(labels1, labels2)
  
  ggplot(jaccard_df) +
    aes(
      x = forcats::fct_rev(id1_label),
      y = id2_label,
      fill = jaccard
    ) +
    geom_tile(color = "grey80") +
    scale_fill_distiller(palette = "RdBu", direction = -1, limits = c(0, 1)) +
    labs(x = labels1_lab, y = labels2_lab, fill = "Jaccard") +
    theme_minimal(base_size = 8) +
    theme(axis.text.x = element_text(angle = 30, hjust = 1))
}

compare_to_ground_truth <- function(res_dataframe, ground_truth_df) {
  res_dataframe |>
    as.data.frame() |>
    tibble::rownames_to_column("barcode") |>
    dplyr::inner_join(ground_truth_df, by = "barcode") |>
    dplyr::select(pruned.labels, ground_truth_label)
}
```


