project_name: maudp_ScPCA
project_docker: cancerbits/dockr:maudp_ScPCAOpen_podman


# SYSTEM-SPECIFIC PARAMETERS (please change to match your local setup):
project_root_host: $CODEBASE/OpenScPCA-analysis/


# PATHS AS VISIBLE WITHIN RSTUDIO (should not be changed):
project_root: /home/rstudio
tmp_root: /home/rstudio/mnt_tmp/

