site_name: OpenScPCA Documentation

exclude_docs: | # syntax: https://www.mkdocs.org/user-guide/configuration/#exclude_docs
  /contributing.md   # docs contribution guidelines
  /requirements.txt  # docs requirements file
  /general-style-guide.md  # docs style guide
  /style-guide-images      # images used in the style guide


theme:
  name: material
  features:
    - content.code.copy      # code copy button in code blocks
    - search.suggest         # displays in light gray how you might complete the word
    - navigation.tabs        # persistent navbar on the top
    - navigation.tabs.sticky # sticky navbar
    - navigation.indexes     # allow index pages to serve as overview pages for sections
    - navigation.sections    # bold headers for directories

plugins:
  - search  # search bar

markdown_extensions:
  - admonition  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#admonition
  - attr_list   # https://github.com/squidfunk/mkdocs-material/blob/master/docs/setup/extensions/python-markdown.md#attribute-lists
  - md_in_html  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#markdown-in-html
  - pymdownx.highlight:  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#configuration
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details     # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#details


# Here is the basic structure of our navigation setup.
#nav:
#  - Navbar section: <!-- Contents for this navbar section are stored in the directory called `section-path` -->
#    - section-path/index.md
#    - section-path/markdown-1.md <!-- left sidebar will display H1 title from the markdown file itself -->
#    - section-path/markdown-2.md
#    - Subsection name: <!-- This title appears as bold item in left sidebar -->
#      - section-path/subsection-path/index.md <!-- summary page for this subsection -->
#      - section-path/subsection-path/markdown-3.md

# Currently, we have templated out the follow navbar items (specific names TBD)
nav:
  - Welcome to OpenScPCA:      # welcome, familiarizing yourself with the project
    - welcome/index.md
  - Technical setup:           # Fork/clone, local environment setup
    - technical-setup/index.md
    - technical-setup/install-a-github-client.md
    - technical-setup/fork-the-repo.md
    - technical-setup/clone-the-repo.md
    - Environment setup:
      - technical-setup/environment-setup/index.md
      - technical-setup/environment-setup/setup-conda.md
      - technical-setup/environment-setup/install-r-rstudio.md
  - Tools for communication:   # Slack, issues, discussions
    - communications-tools/tools-for-communication.md
  - Contributing to analyses:  # Setting up an analysis, all the git stuff
    - contributing-to-analyses/index.md
    - Doing an analysis:
      - contributing-to-analyses/doing-analyses/index.md
    - Working with Git: # Creating branches, adding commits, all git interactions
      - contributing-to-analyses/working-with-git/working-with-branches.md
      - Determining and managing requirements:
        - contributing-to-analyses/determining-and-managing-requirements/index.md
        - contributing-to-analyses/determining-and-managing-requirements/software-requirements.md
  - Software platforms:            # LSfR, AWS, Docker, etc
    - software-platforms/index.md
  - Getting Help and FAQ:      # troubleshooting and FAQ
    - troubleshooting-faq/index.md
  - Policies: # CoC, Authorship, other policies
    - policies/index.md
