site_name: OpenScPCA Documentation

exclude_docs: | # syntax: https://www.mkdocs.org/user-guide/configuration/#exclude_docs
  /contributing.md   # docs contribution guidelines
  /requirements.txt  # docs requirements file
  /general-style-guide.md  # docs style guide
  /style-guide-images      # images used in the style guide


theme:
  name: material
  favicon: img/favicon.svg
  logo: img/ccdlxalsf.svg
  features:
    - content.code.copy      # code copy button in code blocks
    - search.suggest         # displays in light gray how you might complete the word
    - navigation.tabs        # persistent navbar on the top
    - navigation.tabs.sticky # sticky navbar
    - navigation.indexes     # allow index pages to serve as overview pages for sections
    - navigation.sections    # bold headers for directories
    - navigation.footer      # allow users to jump to previous and next doc at the bottom of the page

plugins:
  - search  # search bar

markdown_extensions:
  - admonition  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#admonition
  - attr_list   # https://github.com/squidfunk/mkdocs-material/blob/master/docs/setup/extensions/python-markdown.md#attribute-lists
  - md_in_html  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#markdown-in-html
  - pymdownx.highlight:  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#configuration
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details     # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#details
  - pymdownx.emoji:      # https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AlexsLemonade/OpenScPCA-analysis
      name: OpenScPCA on Github
    - icon: fontawesome/brands/slack
      link: https://ccdatalab.org/slack
      name: Cancer Data Science Slack
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/CancerDataLab
      name: Follow us on X
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/showcase/childhood-cancer-data-lab/
      name: Follow us on LinkedIn

copyright: Copyright &copy; 2024 OpenScPCA Project Maintainers & Contributors | CC-BY 4.0 License

# Here is the basic structure of our navigation setup.
#nav:
#  - Navbar section: <!-- Contents for this navbar section are stored in the directory called `section-path` -->
#    - section-path/index.md
#    - section-path/markdown-1.md <!-- left sidebar will display H1 title from the markdown file itself -->
#    - section-path/markdown-2.md
#    - Subsection name: <!-- This title appears as bold item in left sidebar -->
#      - section-path/subsection-path/index.md <!-- summary page for this subsection -->
#      - section-path/subsection-path/markdown-3.md

# Currently, we have templated out the follow navbar items
# Note that the overall website landing page is in `docs/index.md`.
#  When you locally serve, mkdocs will complain that it isn't in the nav below - this is expected. It should not be in the nav below.
nav:
  - Getting Started:      # welcome, familiarizing yourself with the project
    - getting-started/making-your-first-analysis-contribution.md
    - getting-started/explore-analysis.md
    - Getting Access to Resources:
      - getting-started/accessing-resources/index.md
      - getting-started/accessing-resources/getting-access-to-data.md
      - getting-started/accessing-resources/getting-access-to-compute.md
  - Technical setup:           # Fork/clone, local environment setup
    - technical-setup/index.md
    - technical-setup/install-a-git-client.md
    - technical-setup/fork-the-repo.md
    - technical-setup/clone-the-repo.md
    - Environment setup:
      - technical-setup/environment-setup/index.md
      - technical-setup/environment-setup/setup-conda.md
      - technical-setup/environment-setup/setup-precommit.md
      - technical-setup/environment-setup/configure-aws-cli.md
      - technical-setup/environment-setup/install-docker.md
      - technical-setup/environment-setup/install-r-rstudio.md
  - Tools for communication:   # Slack, issues, discussions
    - communications-tools/index.md
    - GitHub Issues:
      - communications-tools/github-issues/index.md
      - communications-tools/github-issues/writing-issues.md
      - communications-tools/github-issues/what-makes-a-good-issue.md
      - communications-tools/github-issues/issue-templates.md
  - Contributing to analyses:  # Setting up an analysis, all the git stuff
    - contributing-to-analyses/index.md
    - Analysis modules:
      - contributing-to-analyses/analysis-modules/index.md
      - contributing-to-analyses/analysis-modules/creating-a-module.md
      - contributing-to-analyses/analysis-modules/running-a-module.md
      - contributing-to-analyses/analysis-modules/documenting-analysis.md
      - contributing-to-analyses/analysis-modules/notebook-structure.md
    - Determining analysis requirements:
      - contributing-to-analyses/determining-requirements/index.md
      - contributing-to-analyses/determining-requirements/determining-software-requirements.md
      - contributing-to-analyses/determining-requirements/determining-compute-requirements.md
    - Working with Git: # Creating branches, adding commits, all git interactions
      - contributing-to-analyses/working-with-git/index.md
      - contributing-to-analyses/working-with-git/working-with-branches.md
      - contributing-to-analyses/working-with-git/staying-in-sync-with-upstream.md
      - contributing-to-analyses/working-with-git/making-commits.md
      - contributing-to-analyses/working-with-git/troubleshooting-commits.md
      - contributing-to-analyses/working-with-git/push-to-origin.md
    - Creating pull requests:
      - contributing-to-analyses/creating-pull-requests/index.md
      - contributing-to-analyses/creating-pull-requests/scoping-pull-requests.md
      - contributing-to-analyses/creating-pull-requests/pull-request-template.md
      - contributing-to-analyses/creating-pull-requests/resolve-merge-conflicts.md
      - contributing-to-analyses/creating-pull-requests/file-pull-request.md
    - Code review and merging:
      - contributing-to-analyses/pr-review-and-merge/index.md
  - Software platforms:            # LSfR, AWS, Docker, etc
    - software-platforms/index.md
    - Lightsail for Research:
      - software-platforms/lsfr/index.md
    - Amazon S3:
      - software-platforms/aws/index.md
    - Additional project tools:
      - software-platforms/general-tools/index.md
      - software-platforms/general-tools/writing-in-markdown.md
      - software-platforms/general-tools/using-the-terminal.md
  - Getting Help:      # troubleshooting and FAQ
    - troubleshooting-faq/index.md
  - Policies: # CoC, Authorship, other policies
    - policies/index.md
    - policies/terms-of-use.md
    - policies/privacy-policy.md
    - policies/code-of-conduct.md
    - policies/authorship.md
    - policies/SECURITY.md
