name: openscpca-simulate-sce
channels:
  - conda-forge
  - bioconda
platforms:
  - linux-64
  - osx-64
  - osx-arm64
dependencies:
  - python=3.11
  - awscli=2.15
  - jq=1.7
  - conda-lock=2.5
  - pre-commit=3.6
  - session-info=1.0
  - gitpython=3.1
  - anndata
  - pandas
