name: "openscpca-cell-type-ETP-ALL-03"
channels:
  - conda-forge
  - bioconda
platforms:
  - linux-64
  - osx-64
  - osx-arm64
dependencies:
  - python=3.11
  - awscli>=2.15
  - conda-lock>=2.5
  - jq>=1.7
  - pre-commit>=3.6
  - session-info>=1.0
  - leidenalg=0.10
  - dill
  - harmonypy
  - umap-learn
  - pip
  - pip:
      - sam-algorithm==1.0.2
