name: "openscpca-cell-type-neuroblastoma-04"
channels:
  - pytorch
  - conda-forge
  - bioconda
platforms:
  - linux-64
  - osx-arm64
dependencies:
  - python=3.11
  - awscli>=2.15
  - conda-lock>=2.5
  - jq>=1.7
  - pre-commit>=3.6
  - session-info>=1.0
  - anndata
  - scanpy
  - pytorch
  - pip
  - pip:
      - scvi-tools
