name: Start an analysis
description: Use this template to track the any additions or updates to an existing analysis module
labels: analysis
body:
  - type: markdown
    attributes:
      value: |
        **This issue form should be used when you are adding to or updating an existing analysis module.**

        - If you are adding to an existing analysis module that you are actively working on, please proceed to fill out this issue form.
          - If you are looking for more feedback about how to take your next analysis steps, please instead file a Discussion here: <link to general "id like to discuss something" template?">

        - If you are proposing an update to existing analysis module, you should first have a discussion about your proposed update in GitHub Discussions.
        Then, you can link to that thread and use it to help complete this issue.
          - If you have not yet had a GitHub Discussion about this proposed update, please instead file a Discussion here: https://github.com/AlexsLemonade/OpenScPCA-analysis/discussions/new?category=propose-a-new-analysis.

  - type: textarea
    attributes:
      label: If you are filing this issue based on a specific Discussion, please link to the relevant GitHub Discussion.
      description: |
        This does not apply if:
        - You are adding to an existing module that you are the author of
        - You are not seeking additional feedback about the next steps of your analysis
    validations:
      required: false

  - type: textarea
    attributes:
      label: Describe the goals of this analysis module addition.
      description: |
        Summarize the overall scientific goals of this addition, including how it relates to the overall scientific goals of the analysis module.
        Tell us about what the code you plan to add to the module will do.
        This will help guide code review when you file your pull request(s).
    validations:
      required: true

  - type: textarea
    attributes:
      label: Will you require additional software beyond what is already in the analysis module?
      description: |
        Tell us about any new programming language(s) you will use and any new required packages (if known).
    validations:
      required: false

  - type: textarea
    attributes:
      label: What will your pull request contain?
      description: |
        Tell us what code and documentation to expect in the pull request to update the module.
        Remember [that smaller, more focused pull requests get through review faster](STUB_LINK docs on PRs).
    validations:
      required: true

  - type: textarea
    attributes:
      label: Will you require different computational resources beyond what the analysis module already uses?
      description: |
        Please provide any information about any different computational resources requirements for the module.
        This will help us prepare or allocate resources for your analysis.
        For example:

        - Does this analysis require a GPU?
        - Is a certain amount of memory required?
        - Can this be accomplished on a laptop?
    validations:
      required: false

  - type: textarea
    attributes:
      label: If known, when do you expect to file the pull request?
    validations:
      required: false
