name: Perform an analysis
description: Use this template begin a new analysis
labels: analysis
body:
  - type: markdown
    attributes:
      value: |
        This issue form should be used when you are ready to begin performing a new analysis.
        You should only file this issue _after_ you have discussed this analysis on GitHub Discussions.
        You can use the conclusions from your discussion to help answer the questions in this issue form.

        If you have not yet had a discussion about this analysis, please instead file a Discussion here: https://github.com/AlexsLemonade/OpenScPCA-analysis/discussions/.

        If you know who will be performing this analysis, please also use the panel on the right to select the `Assignee`.

  - type: textarea
    attributes:
      label: Please provide a link to the GitHub Discussion for this proposed analysis.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the scientific goals of this analysis.
      description: Please provide a brief description summarizing the scientific question this analysis will address.
    validations:
      required: true

  - type: textarea
    attributes:
      label: What method or approach will be used?
      description: Please provide any specific software dependencies and, of known, their versions that you anticipate using.
    validations:
      required: true

  - type: textarea
    attributes:
      label: What computational resources will be required?
      description: Please provide any information about the required computational resources. For example, does this analysis require a GPU? Is there a certain amount of memory that will be required? Can this be accomplished on a laptop?
    validations:
      required: false

  - type: textarea
    attributes:
      label: What input data are required?
      description: For example, which ScPCA sample(s) or project(s) will this analysis use? Will this use any external data not in ScPCA?
    validations:
      required: false

  - type: textarea
    attributes:
      label: If known, what is the anticipated start date to begin this analysis?
    validations:
      required: false