# This is a workflow to build the docker image for the {{ openscpca_module }} module

# Replace {{ openscpca_module }} throughout the file and otherwise customize to the needs of the particular module

# Docker modules are run on pull requests when code for files that affect the Docker image have changed.
# If other files are used during the Docker build, they should be added to `paths`
#
# At module initialization, this workflow is inactive, and needs to be activated manually

name: Build docker image for {{ openscpca_module }}
env:
  MODULE: "{{ openscpca_module }}"

concurrency:
  # only one run per branch at a time
  group: "{{ openscpca_module }}-${{ github.ref }}"
  cancel-in-progress: true

on:
  # pull_request:
  #   branches:
  #     - main
  #   paths:
  #     - "analyses/{{ openscpca_module }}/Dockerfile"
  #     - "analyses/{{ openscpca_module }}/.dockerignore"
  #     - "analyses/{{ openscpca_module }}/renv.lock"
  #     - "analyses/{{ openscpca_module }}/conda-lock.yml"

jobs:
  build:
    name: Test Build Docker Image
    runs-on: ubuntu-latest

  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}:analyses/${{ env.MODULE }}"
        push: false
        cache-from: type=gha
        cache-to: type=gha,mode=max
