name: Build docker image for {{ MODULE_NAME }}
env:
  MODULE: "{{ MODULE_NAME }}"
  MODULE_PATH: analyses/{{ MODULE_NAME }}
  REGISTRY_ALIAS: openscpca

concurrency:
  # only one run per branch at a time
  group: "{{ MODULE_NAME }}-${{ github.ref }}"
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
    paths:
      - analyses/{{ MODULE_NAME }}/Dockerfile
      - analyses/{{ MODULE_NAME }}/.dockerignore
      - analyses/{{ MODULE_NAME }}/renv.lock
      - analyses/{{ MODULE_NAME }}/conda-lock.yml
  push:
    tags:
      - "v*.*.*"
    branches:
      - main
    paths:
      - analyses/{{ MODULE_NAME }}/Dockerfile
      - analyses/{{ MODULE_NAME }}/.dockerignore
      - analyses/{{ MODULE_NAME }}/renv.lock
      - analyses/{{ MODULE_NAME }}/conda-lock.yml

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::992382809252:role/GithubOpenId
          role-session-name: githubActionSession
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        id: login-ecr
        if: github.event_name == 'push'
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Create ECR repository if needed
        id: create-ecr
        if: github.event_name == 'push'
        run: |
          aws ecr-public describe-repositories --repository-names ${{ env.MODULE }} \
          || aws ecr-public create-repository --repository-name ${{ env.MODULE }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: public.ecr.aws/${{ env.REGISTRY_ALIAS }}/${{ env.MODULE }}
          # tag with semver for releases latest for main branch, ref for prs (tags with branch name)
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{raw}}
            type=ref,event=pr

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:${{ env.MODULE_PATH }}"
          push: ${{ github.event_name == 'push'}}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
