# This is a workflow to run the {{ MODULE_NAME }} module

# Replace {{ MODULE_NAME }} throughout the file and otherwise customize to the needs of the particular module

# Analysis modules are run based on three triggers:
# - Manual trigger
# - On pull requests where code in the module has changed
# - As a reusable workflow called from a separate workflow which periodically runs all modules

name: Run {{ MODULE_NAME }} analysis module
env:
  MODULE_PATH: analyses/{{ MODULE_NAME }}
  AWS_DEFAULT_REGION: us-east-1

concurrency:
  # only one run per branch at a time
  group: {{ MODULE_NAME }}-${{ github.ref }}
  cancel-in-progress: true


on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main
    paths:
      - analyses/{{ MODULE_NAME }}/**


jobs:
  run-module:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Update this step as needed to download the desired data
      - name: Download test data
        run: ./download-data.py --bucket openscpca-temp-simdata --format AnnData --anonymous

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v3

      - name: Install and activate locked conda environment
        run: |
          conda install conda-lock
          conda-lock install --name test ${MODULE_PATH}/conda-lock.yml

      - name: Run analysis module
        run: |
          cd ${MODULE_PATH}
          # run module script here
