# This is a workflow to run the {{MODULE_NAME}} module
# Analysis modules are run based on three triggers:
# - Manual trigger
# - On pull requests where code in the module has changed
# - As a reusable workflow called from a separate workflow which periodically runs all modules

name: Run {{MODULE_NAME}} analysis module
env:
  MODULE_PATH: analyses/{{MODULE_NAME}}
  AWS_DEFAULT_REGION: us-east-1

concurrency:
  # only one run per branch at a time
  group: {{MODULE_NAME}}-${{ github.ref }}
  cancel-in-progress: true


on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main
    paths:
      - analyses/{{MODULE_NAME}}/**


jobs:
  run-module:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Add step to download data here

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.3.3
          use-public-rspm: true

      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2
        with:
          working-directory: ${{ env.MODULE_PATH }}

      - name: Run analysis module
        run: |
          cd ${MODULE_PATH}
          # run module script here
