---
title: "Testing SEACells results"
output: html_notebook
params:
  project_id: "SCPCP000001"
  sample_id: "SCPCS000001"
  library_id: "SCPCL000001"
---


## Setup

```{r setup}
library(ggplot2)
library(reticulate)
reticulate::use_condaenv("openscpca-metacells")
```

```{python imports}
import pathlib
import pickle

import matplotlib
import matplotlib.pyplot as plt
import scanpy as sc
import seaborn as sns
import SEACells
```

## Path definitions

```{r paths}
root_dir <- rprojroot::find_root(rprojroot::is_git_root)
data_dir <- file.path(root_dir, "data", "current")
base_dir <- file.path(root_dir, "analyses", "metacells")
results_dir <- file.path(base_dir, "results", params$project_id, params$sample_id)

ad_file <- file.path(data_dir, params$project_id, params$sample_id, paste0(params$library_id, "_processed_rna.h5ad"))
sc_anndata_file <- file.path(results_dir, paste0(params$library_id, "_seacells.h5ad"))
sc_model_file <- file.path(results_dir, paste0(params$library_id, "_seacells_model.pkl"))


```

## Load SEACells results

```{python load_data}
ad = sc.read(r.ad_file)
sc_ad = sc.read(r.sc_anndata_file)
with open(r.sc_model_file, "rb") as f:
  sc_model = pickle.load(f)
```

```{python}
_ = sns.clustermap(sc_model.kernel_matrix.toarray()[:500, :500])
plt.show()
```

```{python}
SEACells.plot.plot_initialization(sc_ad, sc_model)
```

```{python}
sc_model.plot_convergence()
```


```{python}
SEACells.plot.plot_2D(sc_ad, key="X_umap", colour_metacells=True)
```

```{python}
SEACells.plot.plot_SEACell_sizes(sc_ad, bins=10)
```

```{python}
purity = SEACells.evaluate.compute_celltype_purity(
    sc_ad, "singler_celltype_ontology"
)
```

```{r purity_plot}
ggplot(py$purity, aes(y = singler_celltype_ontology_purity)) +
  geom_boxplot() +
  labs(title = "Celltype purity",
       y = "Celltype purity (singler)")
```
