name: Code styling
on:
  #pull_request:
  #  branches:
  #    - main
  workflow_dispatch:
 #  schedule:
 #    - cron: "0 0 15 1/3 *" # 15th of every 3rd month, for now


concurrency:
  # only one run per branch at a time
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:

  setup-module-matrix:
    runs-on: ubuntu-latest
    name: Setup the module matrix
    outputs:
      matrix: ${{ steps.read-modules.outputs.matrix }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read in list of mature analysis modules
        id: read-modules
        run: |
          # From input `mature-modules.json`, read in modules which should be styled and save to $GITHUB_OUTPUT
          echo "matrix=$(jq -cr . < ./.github/workflows/mature-modules.json)" > $GITHUB_OUTPUT

  style-code:
    runs-on: ubuntu-latest
    name: Perform code styling
    needs: setup-module-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.setup-module-matrix.outputs.matrix) }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      ## First, style the R code ##
      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Install R dependencies
        run: install.packages(c("styler", "knitr", "roxygen2"), repos = "https://p3m.dev/cran/__linux__/jammy/latest")
        shell: Rscript --no-init-file {0}

      - name: Style R code for each analysis module
        run: |
          list.files(
            file.path(
              "analyses",
              "${{ matrix.module }}"
            ),
            recursive = TRUE,
            full.names = TRUE,
            pattern = "\\.(r|rmd)$", ignore.case = TRUE
          ) |>
            # do not style renv/activate.R
            purrr::discard(\(x) grepl("renv/activate.R", x)) |>
            # perform styling
            styler::style_file()
        shell: Rscript --no-init-file {0}

      ## Second, style the python code ##
      - name: Style Python code for each analysis module
        uses: chartboost/ruff-action@v1
        with:
          # TODO: This is grabbing everything under analyses, with and without quotes
          args: format
          src: "analyses/${{ matrix.module }}/"
      - name: Create PR with styled code
        uses: peter-evans/create-pull-request@v6 # defaults to ${GITHUB_TOKEN} token
        with:
          commit-message: Styled code
          signoff: false
          branch: style-module_${{ matrix.module }}
          base: main
          delete-branch: true
          title: "GHA: Automated code styling for analysis module: ${{ matrix.module }}"
          body: |
            ### Description:
            This PR was auto-generated by GitHub Actions to style all R (scripts and notebooks) and Python (scripts only) code in `analyses/${{ matrix.module }}`.

            ### Instruction for reviewers:
            Make sure that all code changes are acceptable.
          labels: |
            OpenScPCA admin
            code styling
