name: Build-Deploy-AWS

on:
  workflow_dispatch:
    branches:
      - main
      - test-cicd

jobs:
  build:

    runs-on: ubuntu-latest
    environment: dev
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
