name: Test Build docker image for simulate-sce
env:
  MODULE: simulate-sce

on:
  pull_request:
    branches:
      - main
    paths:
      - analyses/simulate-sce/Dockerfile
      - analyses/simulate-sce/.dockerignore
      - analyses/simulate-sce/renv.lock
      - analyses/simulate-sce/conda-lock.yml

jobs:
  build:
    name: Test Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:analyses/${{ env.MODULE }}"
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
