# This is a workflow to build the docker image for the hello-clusters module
name: Build docker image for hello-clusters

concurrency:
  # only one run per branch at a time
  group: "docker_hello-clusters_${{ github.ref }}"
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
    paths:
      - analyses/hello-clusters/Dockerfile
      - analyses/hello-clusters/.dockerignore
      - analyses/hello-clusters/renv.lock
      - analyses/hello-clusters/conda-lock.yml
  push:
    branches:
      - main
    paths:
      - analyses/hello-clusters/Dockerfile
      - analyses/hello-clusters/.dockerignore
      - analyses/hello-clusters/renv.lock
      - analyses/hello-clusters/conda-lock.yml
  workflow_dispatch:
    inputs:
      push-ecr:
        description: "Push to AWS ECR"
        type: boolean
        required: true

jobs:
  test-build:
    name: Test Build Docker Image
    if: github.event_name == 'pull_request' || (contains(github.event_name, 'workflow_') && !inputs.push-ecr)
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:analyses/hello-clusters"
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-push:
    name: Build and Push Docker Image
    if: github.repository_owner == 'AlexsLemonade' && (github.event_name == 'push' || inputs.push-ecr)
    uses: ./.github/workflows/build-push-docker-module.yml
    with:
      module: "hello-clusters"
      push-ecr: true
