name: Build docker image for simulate-sce
env:
  MODULE: simulate-sce
  MODULE_PATH: analyses/simulate-sce
  REGISTRY: openscpca

on:
  pull_request:
    branches:
      - main
    paths:
      - analyses/simulate-sce/Dockerfile
      - analyses/simulate-sce/.dockerignore
      - analyses/simulate-sce/renv.lock
      - analyses/simulate-sce/conda-lock.yml
  push:
    branches:
      - jashapiro/docker-simulate-sce
      - main
    # paths:
    #   - analyses/simulate-sce/Dockerfile
    #   - analyses/simulate-sce/.dockerignore
    #   - analyses/simulate-sce/renv.lock
    #   - analyses/simulate-sce/conda-lock.yml

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    environment: "prod"

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::992382809252:role/GithubOpenId
          role-session-name: githubActionSession
          aws-region: us-east-1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: public.ecr.aws/${{ env.REGISTRY }}/${{ env.MODULE }}
          # tag with semver for releases (will also tag latest), edge for main branch
          tags: |
            type=semver,pattern={{raw}}
            type=edge,branch=main

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:${{ env.MODULE_PATH }}"
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=public.ecr.aws/${{ env.REGISTRY }}/${{ env.MODULE }}:buildcache
          cache-to: type=registry,ref=public.ecr.aws/${{ env.REGISTRY }}/${{ env.MODULE }}:buildcache,mode=max
