# This files an issue for creating a release every month on the 6th
name: File create a release issue
on:
  schedule: # run monthly on the 6th (intended to run after all modules are run)
    - cron: 0 0 6 * *

jobs:
  post_issue:
    if: github.repository_owner == 'AlexsLemonade'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set template path
        run: |
          template_path=".github/cron-issue-templates/create-periodic-release-template.md"
          if [ -f "$template_path" ]; then
            echo "TEMPLATE=$template_path" >> $GITHUB_ENV
          else
            echo "File $template_path does not exist"
            exit 1
          fi

      - name: Get date
        run: echo "TODAY=$(date -I)" >> $GITHUB_ENV

      - name: Post issue with results from running all modules
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Create a release: ${{ env.TODAY }}"
          content-filepath: ${{ env.TEMPLATE }}
          labels: release
