name: Pre-commit check
on:
  pull_request:
    branches:
      - main
      - feature/*

jobs:
  pre-commit:
    if: github.repository_owner == 'AlexsLemonade'
    runs-on: ubuntu-latest
    name: Run Pre-commit

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3
