# This is a workflow to all of the analysis module workflows
#
# This workflow will run with the following triggers
# - Manual trigger
# - Periodic running on a timer

name: Run all analysis workflows
on:
  schedule: # run monthly on the 1st
    - cron: "0 0 1 * *"
  workflow_dispatch:
  push:
    branches:
      - jashapiro/104-*

jobs:
  run_hello-R:
    uses: ./.github/workflows/run_hello-R.yml

  run_hello-python:
    uses: ./.github/workflows/run_hello-python.yml

  check-success:
    if: ${{ always() }}
    needs:
      - run_hello-R
      - run_hello-python
    runs-on: ubuntu-latest
    steps:
      - name: check for failures
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: echo job failed && exit 1
