# This is a workflow to run the metacells module
#
# Analysis modules are run based on three triggers:
# - Manual trigger
# - On pull requests where code in the module has changed
# - As a reusable workflow called from a separate workflow which periodically runs all modules
#
# At initialization, only the manual trigger is active

name: Run metacells analysis module
env:
  MODULE_PATH: analyses/metacells
  AWS_DEFAULT_REGION: us-east-2

concurrency:
  # only one run per branch at a time
  group: "run_metacells_${{ github.ref }}"
  cancel-in-progress: true

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main
    paths:
      - analyses/metacells/**
      - "!analyses/metacells/Dockerfile"
      - "!analyses/metacells/.dockerignore"
      - .github/workflows/run_metacells.yml

jobs:
  run-module:
    if: github.repository_owner == 'AlexsLemonade'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.4.0
          use-public-rspm: true

      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2
        with:
          working-directory: ${{ env.MODULE_PATH }}

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest

      - name: Install locked conda environment
        run: |
          conda install conda-lock
          conda-lock install --name openscpca-metacells ${MODULE_PATH}/conda-lock.yml

      # Downloading just one sample for initial testing
      - name: Download test data
        run: ./download-data.py --test-data --format AnnData --sample SCPCS000001

      - name: Run analysis module
        run: |
          cd ${MODULE_PATH}
          conda activate openscpca-metacells
          # run module script here
          bash run-metacells.sh
