# This is a workflow to run the cell-type-ETP-ALL-03 module
#
# Analysis modules are run based on three triggers:
# - Manual trigger
# - On pull requests where code in the module has changed
# - As a reusable workflow called from a separate workflow which periodically runs all modules
#
# At initialization, only the manual trigger is active

name: Run cell-type-ETP-ALL-03 analysis module
env:
  MODULE_PATH: analyses/cell-type-ETP-ALL-03
  AWS_DEFAULT_REGION: us-east-2

concurrency:
  # only one run per branch at a time
  group: "run_cell-type-ETP-ALL-03_${{ github.ref }}"
  cancel-in-progress: true

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main
    paths:
      - analyses/cell-type-ETP-ALL-03/**
      - "!analyses/cell-type-ETP-ALL-03/Dockerfile"
      - "!analyses/cell-type-ETP-ALL-03/.dockerignore"
      - .github/workflows/run_cell-type-ETP-ALL-03.yml

jobs:
  run-module:
    if: github.repository_owner == 'AlexsLemonade'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.4.0
          use-public-rspm: true

      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install system dependencies
        run: |
          sudo apt-get install -y libcurl4-openssl-dev \
            libhdf5-dev \
            libglpk40 \
            libxml2-dev \
            libfontconfig1-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libtiff5-dev

      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2
        with:
          working-directory: ${{ env.MODULE_PATH }}

      - name: Set up conda
      # Note that this creates and activates an environment named 'test' by default
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest

      - name: Install conda-lock and activate locked conda environment
        run: |
          conda install conda-lock
          conda-lock install --name openscpca-cell-type-ETP-ALL-03 ${MODULE_PATH}/conda-lock.yml

      # Update this step as needed to download the desired data
      - name: Download test data
        run: |
          ./download-data.py --projects SCPCP000003 --test-data --format SCE
          ./download-results.py --projects SCPCP000003 --test-data --modules doublet-detection

      - name: Run analysis module
        run: |
          cd ${MODULE_PATH}
          # run module script(s) here
          Rscript scripts/00-01_processing_rds.R
          Rscript scripts/02-03_annotation.R
          Rscript scripts/multipanel_plot.R
