# This is a workflow to run the infercnv-consensus-cell-type module
#
# Analysis modules are run based on three triggers:
# - Manual trigger
# - On pull requests where code in the module has changed
# - As a reusable workflow called from a separate workflow which periodically runs all modules


name: Run infercnv-consensus-cell-type analysis module
env:
  MODULE_PATH: analyses/infercnv-consensus-cell-type
  AWS_DEFAULT_REGION: us-east-2

concurrency:
  # only one run per branch at a time
  group: "run_infercnv-consensus-cell-type_${{ github.ref }}"
  cancel-in-progress: true

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main
    paths:
      - analyses/infercnv-consensus-cell-type/**
      - "!analyses/infercnv-consensus-cell-type/Dockerfile"
      - "!analyses/infercnv-consensus-cell-type/.dockerignore"
      - .github/workflows/run_infercnv-consensus-cell-type.yml

jobs:
  run-module:
    if: github.repository_owner == 'AlexsLemonade'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.4.0
          use-public-rspm: true

      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2
        with:
          working-directory: ${{ env.MODULE_PATH }}

      - name: Install aws-cli
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Install dependencies needed to build certain R packages
        run: |
          sudo apt-get update
          # libcurl4-openssl-dev and lzma-dev are needed for Rhtslib:
          #    https://github.com/samtools/htslib/blob/30c9c50a874059e3dae7ff8c0ad9e8a9258031c8/INSTALL#L31-L41
          # libglpk-dev is needed for igraph
          sudo apt-get install \
            libcurl4-openssl-dev \
            lzma-dev

      - name: Download test data and results
        run: |
          ./download-results.py --module cell-type-ewings --test-data

      - name: Run analysis module
        run: |
          cd ${MODULE_PATH}
          bash run-analysis.sh
