# This is a workflow to run the cell-type-wilms-tumor-14 module
#
# Analysis modules are run based on three triggers:
# - Manual trigger
# - On pull requests where code in the module has changed
# - As a reusable workflow called from a separate workflow which periodically runs all modules
#
# At initialization, only the manual trigger is active

name: Run cell-type-wilms-tumor-14 analysis module
env:
  MODULE_PATH: analyses/cell-type-wilms-tumor-14
  AWS_DEFAULT_REGION: us-east-2

concurrency:
  # only one run per branch at a time
  group: "run_cell-type-wilms-tumor-14_${{ github.ref }}"
  cancel-in-progress: true

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main
    paths:
      - analyses/cell-type-wilms-tumor-14/**
      - "!analyses/cell-type-wilms-tumor-14/Dockerfile"
      - "!analyses/cell-type-wilms-tumor-14/.dockerignore"
      - .github/workflows/run_cell-type-wilms-tumor-14.yml

jobs:
  run-module:
    if: github.repository_owner == 'AlexsLemonade'
    runs-on: ubuntu-latest
    container: public.ecr.aws/openscpca/cell-type-wilms-tumor-14:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install aws-cli
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      # Update this step as needed to download the desired data
      - name: Download test data and results
        run: |
          ./download-data.py --test-data --projects SCPCP000014 --format SCE
          ./download-results.py --test-data --projects SCPCP000014 --modules doublet-detection

      - name: Run analysis module
        run: |
          cd ${MODULE_PATH}
          # run module script
          CI_TESTING=1 bash run_cell-type-wilms-14.sh
