on:
  pull_request:
    branches:
      - main
      - feature/*

name: Check the rOpenScPCA package

jobs:
  R-CMD-check-renv:
    runs-on: ubuntu-22.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.4.0
          use-public-rspm: true

      - name: Remove `.Rprofile` to not activate renv
        run: |
          rm ./packages/rOpenScPCA/.Rprofile

      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2
        with:
          working-directory: "packages/rOpenScPCA/"

      - name: Install additional dependencies for testing
        run: |
          install.packages(c("rcmdcheck", "testthat"))
        shell: Rscript {0}

      - name: Check package
        uses: r-lib/actions/check-r-package@v2
        with:
          working-directory: "packages/rOpenScPCA/"
          args: 'c("--no-manual")'
